### ISSUE TITLE
Добавлние атрибута target="_blank"

### ISSUE THREAD

**Issue by Erghel** [SeryiBaran/seryibaran.github.io#1]
target="_blank" - поможет открыть все переходные ссылки (vk/github/gitlab/youtube и т.д) в новом окне, что он поможет для серфа страницы и изучения вех указанных на сайте ресурсов

Пример использования: 
```
<a href="https://vk.com" target="_blank">Vk</a>
```

**Comment by SeryiBaran** [comment]
Хорошо, исправлю, НО САЙТ ПЕРЕМЕЩАЕТСЯ В НОВЫЙ РЕПОЗИТОРИЙ!

**Comment by Erghel** [comment]
![изображение](https://user-images.githubusercontent.com/88831850/141465865-e7747944-1415-4cbf-9814-03fc3a004ec5.png)

![изображение](https://user-images.githubusercontent.com/88831850/141465890-a72e37fb-2132-4e7a-90f5-54d042758a67.png)

![изображение](https://user-images.githubusercontent.com/88831850/141465919-66450041-c29d-42f7-a4e9-fb655cdeb787.png)

При добавлении атрибута, перех по ссылке будет выглядеть как на 3 фото

**Comment by SeryiBaran** [comment]
Это я понял, исправлю

**Comment by SeryiBaran** [comment]
А, это новый репозиторий

**Comment by SeryiBaran** [comment]
Сайт теперь размещается в этом репозитории, если что

**Comment by SeryiBaran** [comment]
Все сделал.
