### ISSUE TITLE
Скрыть почту

### ISSUE THREAD

**Issue by Erghel** [SeryiBaran/seryibaran.github.io#3]
Чтобы твоя почта не попала в плохие руки, советую его как-то скрыть (значком, сделать из нее ссылку другого вида или как-то иначе)
Потому что есть есть программы, которую с разных сайтов собирают открытого вида почту, а дальше тебе прилетает куча спама, который может не фильтроваться. К чему это может привести - я думаю ясно.

**Comment by SeryiBaran** [comment]
Все готово! Потом сделаю SVG, что-бы мутности не было.

**Comment by SeryiBaran** [comment]
Все готово!

**Comment by Erghel** [comment]
Просто гениальный гений, молодец!

**Comment by SeryiBaran** [comment]
Спасибо, и ты тоже!)
