### ISSUE TITLE
Шрифт/текст

### ISSUE THREAD

**Issue by Erghel** [SeryiBaran/seryibaran.github.io#4]
В разделе "Статьи" открывается текст, и как мне кажется он находится слишком близко друг к другу (это создает некие трудности для чтения), если ты считаешь также, то, возможно, это стоило бы изменить

**Comment by SeryiBaran** [comment]
В смысле близко? Слова друг к другу по горизонтали? Или строки?

**Comment by SeryiBaran** [comment]
Может в статье шрифт поменять?

**Comment by SeryiBaran** [comment]
Но все буду делать завтра - сегодня занят

**Comment by Erghel** [comment]
![image](https://user-images.githubusercontent.com/88831850/141492746-f0acd6c4-37fb-439d-b4f7-8799ab5b932f.jpeg)


Между строчками

**Comment by SeryiBaran** [comment]
Ага, понял

**Comment by Erghel** [comment]
> Может в статье шрифт поменять?

Я думаю да, только если сам хочешь, потому что это мое мнение, что трудно читать. Ты можешь считать и видеть иначе, решение за тобой.

**Comment by SeryiBaran** [comment]
sans-serif лучше

**Comment by SeryiBaran** [comment]
fuck, sans serif'а нету для скачивания

**Comment by SeryiBaran** [comment]
noto sans пусть будет

**Comment by SeryiBaran** [comment]
Готово! Ну как?

**Comment by Erghel** [comment]
Просто отлично, спасибо!
