### ISSUE TITLE
Таблица релизов

### ISSUE THREAD

**Issue by Erghel** [SeryiBaran/seryibaran.github.io#5]
Микро совет, опять же на твое усмотрение - не делать после каждого обновления сайта релиз, да это большое событие, очень понимаю, но это создает лишний "шум", если кто-то захочет посмотреть на проект, делай релизы на что-то масштабное, вот например как сегодня, дизайн поменял, аж глаз радуется. 
А так огромный молодец, очень хороший сайт!

**Comment by SeryiBaran** [comment]
Хорошо! Тегов буду делать поменьше!
